#!/usr/bin/env bash

rm -rf ~/.vim
rm ~/.vimrc
git clone https://github.com/nkj20932/.vim.git ~/.vim
cd ~/.vim
git submodule init
git submodule update --recursive
cp ~/.vim/misc/.vimrc ~/.vimrc
cp ~/.vim/misc/Monokai.vim ~/.vim/bundle/vim-colorschemes/colors/Monokai.vim
echo
echo Done!
